
// Guids.cs - generated by VsctGenerator!
using System;

namespace alexbegh.vMerge.StudioIntegration.Framework
{
    static partial class GuidList
    {
        public static class guidRootTools
        {
            public const string guidString = "{f15bc0ff-40a7-4972-88ab-49930de605b3}";
            public static readonly Guid Guid = new Guid(guidString);
            public const uint idRootToolsGroup = 0x0100;
            public const uint idRootTools = 0x0110;
        }
        public static class ToolsMenu
        {
            public const string guidString = "{ed8b0c70-223d-470f-a44e-03ac40e35539}";
            public static readonly Guid Guid = new Guid(guidString);
            public const uint idToolsVMergeGroup = 0x0100;
            public const uint Id = 0x0110;
            public const uint SwitchToSettings = 0x0120;
            public const uint idVMergeActiveMergeProfileCommandList = 0x0130;
            public const uint idVMergeGroup = 0x0140;
            public const uint ShowWorkItemView = 0x0150;
            public const uint ShowChangesetView = 0x0160;
        }
        public static class guidRootHelp
        {
            public const string guidString = "{792dc125-3e73-451c-bb3e-8712ebb7d04b}";
            public static readonly Guid Guid = new Guid(guidString);
            public const uint idRootHelpGroup = 0x0100;
            public const uint idRootHelp = 0x0110;
            public const uint ShowVMergeHelp = 0x0120;
        }
        public static class guidRootSourceControlExplorerContext
        {
            public const string guidString = "{4fb87b9b-7cf1-49e4-b179-400a3f98606b}";
            public static readonly Guid Guid = new Guid(guidString);
            public const uint idRootSourceControlExplorerContextGroup = 0x0100;
            public const uint idRootSourceControlExplorerContext = 0x0110;
        }
        public static class MergeContextMenu
        {
            public const string guidString = "{2d82c516-22ad-4079-b8e7-9c1444637413}";
            public static readonly Guid Guid = new Guid(guidString);
            public const uint idSourceControlExplorerContextMergeWithVMergeGroup = 0x0100;
            public const uint Id = 0x0110;
            public const uint TargetBranch = 0x0120;
            public const uint idMergeWithVMergeGroup = 0x0163;
            public const uint MatchingProfiles = 0x0173;
            public const uint RefreshBranches = 0x01B6;
        }
        public static class OpenChangesetViewContextMenu
        {
            public const string guidString = "{8005553e-bbc2-4241-94b3-8fd67aca4d12}";
            public static readonly Guid Guid = new Guid(guidString);
            public const uint idSourceControlExplorerContextOPenInVMergeChangesetViewGroup = 0x0100;
            public const uint Id = 0x0110;
            public const uint TargetBranch2 = 0x0120;
        }
    }
}
